### ISSUE TITLE
Strange tuplet bracket angle when first note is rL flam

### ISSUE THREAD

**Issue by ddbrierton** [kastdeur/lilydrum#15]
Hello,

Thank you for this wonderful package. I am not sure if you are still actively maintaining it or not.

When a tuplet begins `\flam gN` the tuplet bracket and number are displayed at an angle:

<img width="172" alt="tuplet" src="https://user-images.githubusercontent.com/7255543/118723171-5ab85100-b82d-11eb-9a9b-8f0552f4e05c.png">

This does not happen if the flam is `\flam dN`(lR) and it only happens when the flam is at the beginning of the tuplet. It does not seem to matter where in the bar the tuplet occurs.

Here is a test case:

```ly
\version "2.20.0"
\include "includes/lilydrum-master/lilydrum.ly"

\score {
  \new PipeBandDrumStaff {
    \drummode {
      \time 2/4
      \tuplet 5/4 {
        \flam g16 d16 g16 d16 g16
      } d4 |
    }
  }
}
```

**Comment by kastdeur** [comment]
Hi ddbrierton!

(This repo currently meets my requirements, so there's little devving from my side at the moment. But I do use it regularly.)

The behaviour is due to the `\stemUp` in [lib/embellishments.ily#L7](https://github.com/kastdeur/lilydrum/blob/8fa01b00e200352ada34085566a32e74d5705232/lib/embellishments.ily#L7) (and other tweaks there like `\small` ).
So lilypond always creates tuplet brackets that are slanted.
 
You can avoid the bracket by moving the `\flam` in front of the `\tuplet` statement. \
 (This is only possible ever since issue #5 was closed.) 
```lilypond
\version "2.20.0"
\include "lilydrum.ly"

\score {
    \new PipeBandDrumStaff {
        \drummode {
            \time 2/4
            \flam \tuplet 5/4 {
                g16 d16 g16 \flam d16 g16
            } d4 |
        }
    }
}
```
![tuplet-test preview](https://user-images.githubusercontent.com/11633260/118729841-e387ba80-b836-11eb-9e89-61b3e35c9c34.png)


It might be possible to fix this in another way (by forcing the bracket some way), but I never pursued such, especially since I like to avoid tuplet brackets anyway :).

---

For future reference, ~~the `\stemUp` statement is really the issue. If the gracenote automatically points up, there is no problem at all (change the `hh16` to see). Even putting the `\stemUp` in the `\grace` statement messes it up.~~

**edit**: Any statement changing properties of the `\grace` environment seems to cause this issue, not the `\stemUp` specifically.

```lilypond
\version "2.20.0"

mygrace = #(define-music-function (parser location notes) (ly:music?) #{
    \stemUp
    \grace { $notes }
    \stemNeutral
#})

\new DrumStaff {
    \drummode {
        \time 2/4
        \tuplet 5/4 {
            \mygrace {hh16} sn16 16 16 16 16
        } 4 |
    }
}
```
With `\stemUp`:
![tuplet-test-ly preview](https://user-images.githubusercontent.com/11633260/118730248-922bfb00-b837-11eb-93f3-fccfa904a0e4.png)

Without `\stemUp`:
![tuplet-test-ly preview](https://user-images.githubusercontent.com/11633260/118730203-85a7a280-b837-11eb-802a-a05109ad9734.png)

**Comment by ddbrierton** [comment]
Hi!

Thank you for you swift response. Unfortunately moving the `\flam` outside the `\tuple` worked for the simple test case but not in the actual case I was working on:

```ly
\version "2.20.0"
\include "includes/lilydrum-master/lilydrum.ly"

\score {
  \new PipeBandDrumStaff {
    \drummode {
      \time 2/4
      \tuplet 5/4 4 {
        \flam d16 g16 d16 g16 d16
      }
      \tuplet 5/4 4 \flam {
        g16 d16 g16 d16 g16
      } |
    }
  }
}
```

<img width="226" alt="Screenshot 2021-05-19 at 12 55 24" src="https://user-images.githubusercontent.com/7255543/118801610-7fe6a700-b8a1-11eb-9671-ac5c35b18a79.png">

I’m not really bothered by the brackets, I can switch them off (normally I just let Lilypond decide whether to draw them or not) but the “5” is still misaligned and rather far from the beam for good readability.

It seems to me that Lilypond is extending the bracket to include the grace note when it probably shouldn’t. I just tried writing the same thing in Dorico, switched on brackets and indeed it doesn’t not extend the bracket leftwards to include the grace note. So perhaps this is a Lilypond bug?

**Comment by ddbrierton** [comment]
Hi

Thank you for your swift response. (I deleted an earlier response when I later realised I had misapplied your workaround.) Indeed placing the opening `\flam` outside the `\tuplet` works and is an acceptable solution for me.

Thanks again.

**Comment by kastdeur** [comment]
Glad to be of help :+1:  \
(aswell as to see somebody's using it)
